[build]
  # No build command - using pre-built files from build/web
  # Build locally with: flutter build web --release
  publish = "build/web"

# Handle single-page application routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Note: Headers are now configured in build/web/_headers file 